site_name: localassistant
site_url: !ENV READTHEDOCS_CANONICAL_URL
site_author: Linos1391
site_description: Localassistant (locas) is just a local AI, and to me, is the local AI.

copyright: Copyright &copy; 2024 - 2026 Linos1391

repo_name: localassistant
repo_url: https://github.com/Linos1391/localassistant

nav:
  - Home: index.md
  - Installation: installation.md
  # - Models: models.md
  # - Commands: commands.md

extra_javascript:
  - javascript/readthedocs.js

theme:
  name: material
  logo: asset/icon.png
  favicon: asset/icon.png
  palette:
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Linos1391

